# -*- coding: utf-8 -*-
"""factorial_recursivo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d2QOdqQBg0EDYNe-OMwuawrpkOYU2ht8
"""

def factorial(n):
  """ factorial de n
      
      n int cualquier entero
      returns el factorial de n
      """
  if n == 1:
    return n
  
  return n * factorial(n-1)



n = int(input("DiGite un numero entero: "))
print(factorial(n))